"""
tools/pdf_tools.py

PDF generation tool for StoryLens.
Takes story pages + illustration image URLs and assembles
into a beautiful children's book PDF.

Used by book_publisher agent via @tool decorator.
"""

import os
import re
import requests
from fpdf import FPDF
from crewai.tools import tool


def clean_text(text: str) -> str:
    """
    Replace Unicode characters not supported by Helvetica with ASCII equivalents.
    FPDF with Helvetica only supports Latin-1 charset.
    """
    if not text:
        return text
    # Smart quotes -> straight quotes
    text = text.replace("‘", "'").replace("’", "'")
    text = text.replace("“", '"').replace("”", '"')
    # Em dash, en dash -> hyphen
    text = text.replace("—", "--").replace("–", "-")
    # Ellipsis -> three dots
    text = text.replace("…", "...")
    # Common emoji replacements
    text = text.replace("❤", "<3").replace("️", "")
    text = text.replace("📚", "").replace("✨", "*")
    # Remove any remaining non-Latin-1 characters
    text = text.encode("latin-1", errors="ignore").decode("latin-1")
    return text


class StoryBookPDF(FPDF):
    """Custom FPDF class for children's book formatting."""

    def __init__(self, book_title: str, child_name: str):
        super().__init__(orientation="P", unit="mm", format="A4")
        self.book_title = book_title
        self.child_name = child_name
        self.set_auto_page_break(auto=True, margin=15)

    def cover_page(self, title: str, child_name: str):
        """Generate a colorful cover page."""
        self.add_page()
        # Background color — soft yellow
        self.set_fill_color(255, 250, 200)
        self.rect(0, 0, 210, 297, "F")

        # Title
        self.set_font("Helvetica", "B", 28)
        self.set_text_color(50, 100, 200)
        self.set_y(80)
        self.multi_cell(0, 12, clean_text(title), align="C")

        # Dedication
        self.set_font("Helvetica", "I", 16)
        self.set_text_color(100, 100, 100)
        self.set_y(140)
        self.cell(0, 10, clean_text(f"A story just for {child_name}"), align="C", new_x="LMARGIN", new_y="NEXT")

        # Generated by
        self.set_font("Helvetica", "", 12)
        self.set_text_color(150, 150, 150)
        self.set_y(260)
        self.cell(0, 10, "Generated with love by StoryLens AI", align="C")

    def story_page(
        self,
        page_number: int,
        title: str,
        text: str,
        image_url: str = None,
    ):
        """Generate a single story page with optional illustration."""
        self.add_page()

        # Soft background per page — alternating colors
        colors = [
            (230, 245, 255),  # light blue
            (230, 255, 230),  # light green
            (255, 240, 230),  # light orange
            (245, 230, 255),  # light purple
            (255, 255, 220),  # light yellow
        ]
        color = colors[page_number % len(colors)]
        self.set_fill_color(*color)
        self.rect(0, 0, 210, 297, "F")

        # Page number
        self.set_font("Helvetica", "", 10)
        self.set_text_color(150, 150, 150)
        self.set_y(10)
        self.cell(0, 6, f"Page {page_number}", align="R", new_x="LMARGIN", new_y="NEXT")

        # Image height — fits within page with room for text below
        IMG_X = 20
        IMG_Y = 18
        IMG_W = 170
        IMG_H = 150  # fixed height — text starts below this

        # Illustration — local file path or URL
        if image_url:
            try:
                if image_url.startswith("/") or image_url.startswith("./"):
                    if os.path.exists(image_url):
                        self.image(image_url, x=IMG_X, y=IMG_Y, w=IMG_W, h=IMG_H)
                else:
                    img_path = f"/tmp/storylens_page_{page_number}.png"
                    response = requests.get(image_url, timeout=10)
                    if response.status_code == 200:
                        with open(img_path, "wb") as f:
                            f.write(response.content)
                        self.image(img_path, x=IMG_X, y=IMG_Y, w=IMG_W, h=IMG_H)
            except Exception:
                pass
        else:
            # No image — placeholder box
            self.set_draw_color(200, 200, 200)
            self.set_fill_color(240, 240, 240)
            self.rect(IMG_X, IMG_Y, IMG_W, IMG_H, "DF")

        # Text always starts at fixed Y below image — no overlap
        TEXT_Y = IMG_Y + IMG_H + 6
        self.set_y(TEXT_Y)

        # Page title
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(50, 100, 200)
        self.multi_cell(0, 9, clean_text(title), align="C")
        self.ln(3)

        # Story text
        self.set_font("Helvetica", "", 13)
        self.set_text_color(50, 50, 50)
        self.multi_cell(0, 7, clean_text(text), align="C")

    def back_page(self, moral: str):
        """Generate the back page with the book's moral."""
        self.add_page()
        self.set_fill_color(200, 230, 255)
        self.rect(0, 0, 210, 297, "F")

        self.set_font("Helvetica", "B", 20)
        self.set_text_color(50, 100, 200)
        self.set_y(100)
        self.cell(0, 12, "What we learned today:", align="C", new_x="LMARGIN", new_y="NEXT")

        self.ln(10)
        self.set_font("Helvetica", "I", 16)
        self.set_text_color(80, 80, 80)
        self.multi_cell(0, 10, clean_text(moral), align="C")

        self.set_y(250)
        self.set_font("Helvetica", "", 11)
        self.set_text_color(150, 150, 150)
        self.cell(0, 8, "Made with StoryLens AI", align="C")


def build_safe_prompt(original_prompt: str, page_title: str, page_text: str) -> str:
    """
    Build a DALL-E safe prompt.
    Avoids detailed child appearance descriptions that trigger safety filters.
    Uses cartoon/illustration style instead.
    """
    # Extract scene description — ignore appearance details
    # Focus on the ACTION and SETTING not the character appearance
    safe_prompt = (
        f"Children's book illustration, cute cartoon style, bright warm colors, "
        f"simple friendly art like a picture book. "
        f"Scene: {page_title}. "
        f"Soft pastel background, no text, safe for toddlers. "
        f"Pixar-style friendly illustration."
    )
    return safe_prompt[:900]


def generate_dalle_image(prompt: str, page_number: int, title: str = "", text: str = "") -> str | None:
    """Generate a DALL-E image for a story page. Returns local path or None."""
    try:
        from openai import OpenAI
        client = OpenAI()

        # Use safe prompt that won't trigger content policy
        safe_prompt = build_safe_prompt(prompt, title, text)

        response = client.images.generate(
            model="dall-e-3",
            prompt=safe_prompt,
            size="1024x1024",
            quality="standard",
            n=1,
        )

        image_url = response.data[0].url
        img_path = f"/tmp/storylens_page_{page_number}.png"
        img_response = requests.get(image_url, timeout=30)
        if img_response.status_code == 200:
            with open(img_path, "wb") as f:
                f.write(img_response.content)
            return img_path
        return None
    except Exception as e:
        print(f"DALL-E generation failed for page {page_number}: {e}")
        return None


@tool("Generate Children's Book PDF")
def generate_pdf(
    book_title: str,
    child_name: str,
    central_moral: str,
    pages_json: str,
) -> str:
    """
    Generates a PDF children's book from story pages.
    Calls DALL-E to generate illustrations for each page.

    Args:
        book_title:     Title of the book
        child_name:     Name of the child hero
        central_moral:  The overall moral of the story
        pages_json:     JSON string of pages with title, text,
                        and optionally illustration_prompt per page

    Returns:
        Path to the generated PDF file, or error message.
    """
    import json

    try:
        pages = json.loads(pages_json)
    except Exception as e:
        return f"Error parsing pages JSON: {str(e)}"

    try:
        pdf = StoryBookPDF(book_title=book_title, child_name=child_name)

        # Cover page
        pdf.cover_page(title=book_title, child_name=child_name)

        # Story pages — generate DALL-E image for each
        for i, page in enumerate(pages):
            page_number = page.get("page_number") or (i + 1)
            title = page.get("title", "")
            text = page.get("text", "")
            illustration_prompt = page.get("illustration_prompt") or page.get("prompt", "")

            # Generate illustration if prompt available
            image_path = None
            if illustration_prompt:
                image_path = generate_dalle_image(
                    illustration_prompt, page_number,
                    title=title, text=text
                )

            pdf.story_page(
                page_number=page_number,
                title=title,
                text=text,
                image_url=image_path,  # local path now instead of URL
            )

        # Back page with moral
        pdf.back_page(moral=central_moral)

        # Save PDF
        os.makedirs("output", exist_ok=True)
        safe_name = child_name.lower().replace(" ", "_")
        pdf_path = f"output/{safe_name}_storylens_book.pdf"
        pdf.output(pdf_path)

        return pdf_path

    except Exception as e:
        return f"Error generating PDF: {str(e)}"